runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
- url: /.*
  script: final.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
  